import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-green-400 font-mono`}>
        <div className="flex flex-col min-h-screen relative">
          <main className="flex-1">
            {children}
          </main>
          <footer className="w-full text-center text-sm py-2 absolute bottom-0">
            <span className="text-green-400 font-mono">Built by Santi</span>
          </footer>
        </div>
      </body>
    </html>
  );
}
